import { Providers } from '@/redux/provider'
import './globals.css'
import Footer from '@/components/Footer'

export const metadata = {
  title: 'Aviator Ascent',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          {children}
          <Footer />
          </Providers>
      </body>
    </html>
  )
}
