import { Providers } from '@/redux/provider'
import './globals.css'
import Footer from '@/components/global/Footer'
import NotificationContainer from '@/components/global/NotificationContainer'



export const metadata = {
  title: 'Aviator Ascent',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
          <Providers>
            {children}
            <NotificationContainer />
          </Providers>
      </body>
    </html>
  )
}
